AWSTemplateFormatVersion: 2010-09-09
Description: AWS Serverless Websocket Sample - Websocket Stack

Transform:
  - AWS::Serverless-2016-10-31


Resources:
  # Creates S3 Bucket for store SAM/CloudFormation templates
  WebsocketTemplateBucket:
    Type: AWS::S3::Bucket
    
Outputs:
  WebsocketTemplateBucketARN:
    Description: S3 Bucket ARN
    Value: 
      Fn::GetAtt:
        - WebsocketTemplateBucket
        - Arn
    Export: 
      Name: !Sub ${AWS::StackName}:WebsocketTemplateBucketARN
  WebsocketTemplateBucketName:
    Description: S3 Bucket Name
    Value:
      Ref: WebsocketTemplateBucket
    Export:
      Name: !Sub ${AWS::StackName}:WebsocketTemplateBucketName